copy ctm_fbi.mdl ctm_fbi_varianta.mdl
copy ctm_fbi.vvd ctm_fbi_varianta.vvd
copy ctm_fbi.phy ctm_fbi_varianta.phy
copy ctm_fbi.dx90.vtx ctm_fbi_varianta.dx90.vtx 
copy ctm_fbi.mdl ctm_fbi_variantb.mdl
copy ctm_fbi.vvd ctm_fbi_variantb.vvd
copy ctm_fbi.phy ctm_fbi_variantb.phy
copy ctm_fbi.dx90.vtx ctm_fbi_variantb.dx90.vtx 
copy ctm_fbi.mdl ctm_fbi_variantc.mdl
copy ctm_fbi.vvd ctm_fbi_variantc.vvd
copy ctm_fbi.phy ctm_fbi_variantc.phy
copy ctm_fbi.dx90.vtx ctm_fbi_variantc.dx90.vtx 
copy ctm_fbi.mdl ctm_fbi_variantd.mdl
copy ctm_fbi.vvd ctm_fbi_variantd.vvd
copy ctm_fbi.phy ctm_fbi_variantd.phy
copy ctm_fbi.dx90.vtx ctm_fbi_variantd.dx90.vtx 
copy ctm_fbi.mdl ctm_fbi_variante.mdl
copy ctm_fbi.vvd ctm_fbi_variante.vvd
copy ctm_fbi.phy ctm_fbi_variante.phy
copy ctm_fbi.dx90.vtx ctm_fbi_variante.dx90.vtx 
copy ctm_fbi.mdl ctm_fbi_variantf.mdl
copy ctm_fbi.vvd ctm_fbi_variantf.vvd
copy ctm_fbi.phy ctm_fbi_variantf.phy
copy ctm_fbi.dx90.vtx ctm_fbi_variantf.dx90.vtx 
copy ctm_fbi.mdl ctm_fbi_variantg.mdl
copy ctm_fbi.vvd ctm_fbi_variantg.vvd
copy ctm_fbi.phy ctm_fbi_variantg.phy
copy ctm_fbi.dx90.vtx ctm_fbi_variantg.dx90.vtx 
copy ctm_fbi.mdl ctm_fbi_varianth.mdl
copy ctm_fbi.vvd ctm_fbi_varianth.vvd
copy ctm_fbi.phy ctm_fbi_varianth.phy
copy ctm_fbi.dx90.vtx ctm_fbi_varianth.dx90.vtx 
